const mongoose = require("mongoose");

// Define the User schema
const userSchema = new mongoose.Schema({
  // ID field will be automatically generated by MongoDB
  username: String, // You can use 'username' instead of 'email' if you prefer
  password: String,
  email: String,
  groups: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Group", // Reference to the Group model
    },
  ],
});

// Create the User model
const User = mongoose.model("User", userSchema);

// Export the User model
module.exports = User;
